// src/domain/events/event.types.ts

/**
 * CANONICAL EVENT TYPE UNION - SINGLE SOURCE OF TRUTH (ECS v1.3)
 * All event types must be defined here. This is the only place EventType is declared.
 */

export type EventType =
  | "CUSTOMER_CHECKED_IN"
  | "BARBER_AVAILABLE"
  | "CUSTOMER_CALLED_TO_CHAIR"
  | "SERVICE_ENGAGED"
  | "SERVICE_COMPLETED"
  | "PAYMENT_INTENT_CREATED"
  | "PAYMENT_PROCESSING"
  | "PAYMENT_SETTLED"
  | "ADJUSTMENT_EVENT"
  | "ACCOUNT_VERIFIED"
  | "QUEUE_TRANSFER_CONSENTED"
  | "APPOINTMENT_RESERVED"
  | "RESERVATION_CANCELLED"
  | "SERVICE_INTENT_ADDED"
  | "SERVICE_INTENT_REMOVED"
  | "BARBER_SCHEDULE_UPDATED"
  | "SHOP_HOURS_CHANGED"
  | "OPERATOR_SESSION_OPENED"
  | "OPERATOR_SESSION_CLOSED"
  | "SYNC_BATCH_ACKNOWLEDGED"
  | "RECONCILIATION_ANOMALY_DETECTED"
  | "LOCAL_SNAPSHOT_COMMITTED"
  | "TERMINAL_RECOVERY_COMPLETED"
  | "RESERVATION_EXPIRED";
